package com.msdtt.framework.model;

import java.io.Serializable;
import java.math.BigDecimal;
import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class MonthlyCreditOrderDaysPosition implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_credit_order_days_position.monthly
     * 
     */
    private Integer monthly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_credit_order_days_position.order_no
     * 
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_credit_order_days_position.position
     * 
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_credit_order_days_position.days
     * 
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_credit_order_days_position.amount
     * 
     */
    private BigDecimal amount;

    /**
     * monthly_credit_order_days_position表的操作属性:serialVersionUID
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 数据字段 monthly_credit_order_days_position.monthly的get方法 
     * 
     */
    public Integer getMonthly() {
        return monthly;
    }

    /**
     * 数据字段 monthly_credit_order_days_position.monthly的set方法
     * 
     */
    public void setMonthly(Integer monthly) {
        this.monthly = monthly;
    }

    /**
     * 数据字段 monthly_credit_order_days_position.order_no的get方法 
     * 
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * 数据字段 monthly_credit_order_days_position.order_no的set方法
     * 
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * 数据字段 monthly_credit_order_days_position.position的get方法 
     * 
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * 数据字段 monthly_credit_order_days_position.position的set方法
     * 
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * 数据字段 monthly_credit_order_days_position.days的get方法 
     * 
     */
    public Integer getDays() {
        return days;
    }

    /**
     * 数据字段 monthly_credit_order_days_position.days的set方法
     * 
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * 数据字段 monthly_credit_order_days_position.amount的get方法 
     * 
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * 数据字段 monthly_credit_order_days_position.amount的set方法
     * 
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}